export const APP_NAME = 'ULIONG';
export const APP_TAGLINE = 'AI Threat Intelligence Platform';

export const SAMPLE_SCANS = [
  {
    id: '1',
    scanType: 'text' as const,
    inputContent: 'Urgent: Your account has been compromised. Click here to verify your password immediately.',
    riskScore: 87,
    riskLevel: 'high_risk' as const,
    threatIndicators: [
      { name: 'Urgency Language', detected: true, severity: 'high' as const, description: 'Message uses urgent language to pressure the recipient.' },
      { name: 'Suspicious Link', detected: true, severity: 'high' as const, description: 'Contains a link to a known phishing domain.' },
      { name: 'Spoofed Sender', detected: true, severity: 'medium' as const, description: 'Sender address does not match the claimed organisation.' },
      { name: 'Grammar Errors', detected: false, severity: 'low' as const, description: 'No significant grammatical errors detected.' },
      { name: 'Request for Credentials', detected: true, severity: 'high' as const, description: 'Directly asks for password or login credentials.' },
    ],
    aiExplanation: 'This message exhibits classic phishing characteristics: it creates a sense of urgency, claims an account compromise, directs the user to a suspicious link, request for credentials. High pressure tactics combined with the request for credentials make this almost certainly a phishing attempt.',
    recommendedAction: 'Do not click any links. Report this message to your security team immediately. If you have already clicked the link, run a full security scan and change your passwords.',
    confidenceLevel: 0.96,
    pipelineStages: {},
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: '2',
    scanType: 'url' as const,
    inputContent: 'https://securen-bank-login.xyz/verify',
    riskScore: 94,
    riskLevel: 'high_risk' as const,
    threatIndicators: [
      { name: 'Suspicious TLD', detected: true, severity: 'high' as const, description: 'Uses a .xyz TLD commonly used for malicious sites.' },
      { name: 'Misspelled Domain', detected: true, severity: 'high' as const, description: '"securen-bank" is a misspelling of a legitimate bank domain.' },
      { name: 'Excessive Subdirectories', detected: true, severity: 'medium' as const, description: 'Uses subdirectories to mimic a legitimate login page.' },
      { name: 'HTTPS Certificate', detected: false, severity: 'low' as const, description: 'Uses HTTPS, but certificates can be obtained by anyone.' },
      { name: 'Known Malicious', detected: true, severity: 'high' as const, description: 'Domain has been reported in threat intelligence feeds.' },
    ],
    aiExplanation: 'This URL is designed to impersonate a banking login page. The domain uses a .xyz TLD and misspells a legitimate bank domain, with a "/verify" path to trick users into entering credentials.',
    recommendedAction: 'Block this domain immediately. Notify your security team. Check for users who may have visited this URL.',
    confidenceLevel: 0.98,
    pipelineStages: {},
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: '3',
    scanType: 'text' as const,
    inputContent: 'Your package delivery has been suspended due to incomplete address information. Please update your delivery preferences at the following link to avoid return to sender.',
    riskScore: 62,
    riskLevel: 'suspicious' as const,
    threatIndicators: [
      { name: 'Urgency Language', detected: true, severity: 'medium' as const, description: 'Creates urgency about package delivery suspension.' },
      { name: 'Suspicious Link', detected: true, severity: 'medium' as const, description: 'Contains a shortened URL that obscures the destination.' },
      { name: 'Spoofed Sender', detected: false, severity: 'low' as const, description: 'Sender domain appears legitimate.' },
      { name: 'Generic Greeting', detected: true, severity: 'low' as const, description: 'Uses a generic greeting rather than addressing the recipient by name.' },
      { name: 'Request for Personal Info', detected: true, severity: 'medium' as const, description: 'Asks for address and personal information.' },
    ],
    aiExplanation: 'This message mimics a delivery notification but contains red flags: generic greeting, urgency about package suspension, and a request to click a shortened link — common delivery-scam tactics.',
    recommendedAction: 'Verify the tracking number with the shipping company directly. Do not use the provided link. Forward suspicious messages to your security team.',
    confidenceLevel: 0.78,
    pipelineStages: {},
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: '4',
    scanType: 'url' as const,
    inputContent: 'https://www.google.com',
    riskScore: 5,
    riskLevel: 'safe' as const,
    threatIndicators: [
      { name: 'Suspicious TLD', detected: false, severity: 'low' as const, description: 'Uses a standard .com TLD.' },
      { name: 'Misspelled Domain', detected: false, severity: 'low' as const, description: 'Domain is correctly spelled and matches the legitimate service.' },
      { name: 'HTTPS Certificate', detected: true, severity: 'low' as const, description: 'Valid HTTPS certificate from a trusted CA.' },
      { name: 'Known Malicious', detected: false, severity: 'low' as const, description: 'Domain is not listed in threat intelligence feeds.' },
      { name: 'Suspicious Redirects', detected: false, severity: 'low' as const, description: 'No suspicious redirect chains detected.' },
    ],
    aiExplanation: 'This URL is a well-known, legitimate domain with a valid certificate and no history of malicious activity. It appears safe.',
    recommendedAction: 'No action required. This URL appears safe.',
    confidenceLevel: 0.99,
    pipelineStages: {},
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: '5',
    scanType: 'text' as const,
    inputContent: 'Hi team, just a reminder that the quarterly review meeting is scheduled for next Tuesday at 10 AM. Please prepare your updates.',
    riskScore: 3,
    riskLevel: 'safe' as const,
    threatIndicators: [
      { name: 'Urgency Language', detected: false, severity: 'low' as const, description: 'No urgent or pressured language detected.' },
      { name: 'Suspicious Link', detected: false, severity: 'low' as const, description: 'No links present in the message.' },
      { name: 'Spoofed Sender', detected: false, severity: 'low' as const, description: 'Sender appears to be a known internal contact.' },
      { name: 'Request for Sensitive Info', detected: false, severity: 'low' as const, description: 'No request for sensitive information.' },
      { name: 'Unusual Sender', detected: false, severity: 'low' as const, description: 'Sender matches expected communication patterns.' },
    ],
    aiExplanation: 'Standard internal meeting reminder with professional language, no links, and no sensitive-information requests. Appears safe.',
    recommendedAction: 'No action required. This message appears safe.',
    confidenceLevel: 0.99,
    pipelineStages: {},
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
  {
    id: '6',
    scanType: 'url' as const,
    inputContent: 'http://bit.ly/3xK9mPn',
    riskScore: 45,
    riskLevel: 'suspicious' as const,
    threatIndicators: [
      { name: 'URL Shortener', detected: true, severity: 'medium' as const, description: 'Uses a URL shortening service that obscures the final destination.' },
      { name: 'No HTTPS', detected: true, severity: 'medium' as const, description: 'Does not use HTTPS encryption.' },
      { name: 'Known Malicious', detected: false, severity: 'low' as const, description: 'Not currently in threat feeds, but could be new.' },
    ],
    aiExplanation: 'This shortened URL obscures its destination. Without HTTPS and inability to verify the destination, this is suspicious. Shorteners are commonly abused for phishing.',
    recommendedAction: 'Use a URL expander to preview the destination before clicking. If unknown or suspicious, do not proceed.',
    confidenceLevel: 0.65,
    pipelineStages: {},
    createdAt: new Date(Date.now() - 3600000 * 96).toISOString(),
  },
  {
    id: '7',
    scanType: 'text' as const,
    inputContent: 'Congratulations! You have been selected as the winner of our annual raffle! Claim your prize of $500,000 by clicking the link below and providing your bank details for the transfer.',
    riskScore: 91,
    riskLevel: 'high_risk' as const,
    threatIndicators: [
      { name: 'Prize/Lottery Scam', detected: true, severity: 'high' as const, description: 'Claims the recipient won a prize they did not enter.' },
      { name: 'Urgency Language', detected: true, severity: 'high' as const, description: 'Creates excitement and urgency to claim the prize.' },
      { name: 'Request for Bank Details', detected: true, severity: 'high' as const, description: 'Directly asks for sensitive banking information.' },
      { name: 'Suspicious Link', detected: true, severity: 'high' as const, description: 'Contains a link to a known scam domain.' },
      { name: 'Unsolicited Message', detected: true, severity: 'medium' as const, description: 'Recipient did not enter any raffle.' },
    ],
    aiExplanation: 'Classic advance-fee fraud / lottery scam: promises a large sum the recipient never entered for, and requests bank details to process the transfer. Legitimate prizes never require fees or bank details upfront.',
    recommendedAction: 'Do not respond. Do not click links. Block and report. If bank details were provided, contact your bank immediately.',
    confidenceLevel: 0.97,
    pipelineStages: {},
    createdAt: new Date(Date.now() - 3600000 * 120).toISOString(),
  },
  {
    id: '8',
    scanType: 'url' as const,
    inputContent: 'https://github.com/facebook/react',
    riskScore: 2,
    riskLevel: 'safe' as const,
    threatIndicators: [
      { name: 'Suspicious TLD', detected: false, severity: 'low' as const, description: 'Uses standard .com TLD.' },
      { name: 'Known Repository', detected: true, severity: 'low' as const, description: 'Links to a well-known open-source project.' },
      { name: 'HTTPS Certificate', detected: true, severity: 'low' as const, description: 'Valid HTTPS certificate.' },
      { name: 'Malicious Content', detected: false, severity: 'low' as const, description: 'No known malicious content associated with this URL.' },
    ],
    aiExplanation: 'This is a legitimate GitHub repository URL for the React library. Domain is well-known, certificate valid, no malicious history.',
    recommendedAction: 'No action required. This URL appears safe.',
    confidenceLevel: 0.99,
    pipelineStages: {},
    createdAt: new Date(Date.now() - 3600000 * 168).toISOString(),
  },
] as const;
       
