import { useState } from 'react';
import { Button, Card, CardContent, CardHeader } from '../components/ui';
import { useSettingsStore } from '../stores/settingsStore';
import type { AiProvider } from '../types';

export function SettingsPage() {
  const { settings, updateAiProvider, updateNotification, updateSecurity, resetSettings } = useSettingsStore();
  const [saved, setSaved] = useState(false);
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 1500); };
  return <div className="p-4 sm:p-6 lg:p-8 max-w-3xl mx-auto"><Card><CardHeader><h1 className="text-xl font-semibold text-text-primary">Settings</h1><p className="text-sm text-text-muted">Provider selection and local UI preferences. Provider credentials are server-side only.</p></CardHeader><CardContent className="space-y-6"><div><p className="text-sm font-medium text-text-secondary mb-2">Analysis provider</p><div className="flex gap-2">{(['openai', 'gemini'] as AiProvider[]).map((provider) => <button key={provider} type="button" onClick={() => updateAiProvider(provider)} className={`flex-1 rounded-lg border p-3 text-left ${settings.aiProvider === provider ? 'border-accent-blue bg-accent-blue/10' : 'border-white/10'}`}><span className="text-sm text-text-primary">{provider === 'openai' ? 'OpenAI' : 'Google Gemini'}</span><span className="block text-xs text-text-muted">Configured by the analysis service</span></button>)}</div></div><div className="space-y-3">{(Object.entries(settings.notifications) as [keyof typeof settings.notifications, boolean][]).map(([key, value]) => <label key={key} className="flex items-center justify-between text-sm text-text-secondary"><span>{key}</span><input type="checkbox" checked={value} onChange={(event) => updateNotification(key, event.target.checked)} /></label>)}</div><div className="space-y-3">{(['autoBlockHighRisk', 'requireConfirmation', 'logAllAnalyses'] as const).map((key) => <label key={key} className="flex items-center justify-between text-sm text-text-secondary"><span>{key}</span><input type="checkbox" checked={settings.security[key]} onChange={(event) => updateSecurity(key, event.target.checked)} /></label>)}</div><div className="flex gap-3"><Button onClick={save}>{saved ? 'Saved' : 'Save preferences'}</Button><Button variant="danger" onClick={resetSettings}>Reset</Button></div></CardContent></Card></div>;
}
